version: "3.7"
services:
  oxygen:
    container_name: oxygen-frontend
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - 3000:3000
    command: yarn start
